---
- hosts: 172.31.12.205
  become: yes
  tasks:
  - include_tasks: file.yml
  - name: install webserver
    apt:
     name: apache2
     state: present
  - name: want to send static file to ansible nodes
    copy:
      src: static.txt
      dst: /home/ubuntu/static.txt

  - name: want to send dynamic file to ansible nodes
    template:
       src: dynamic
       dst: /var/www/html/index.html
   