---
- hosts: webservers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name:
      state: present
    when: ansible_os_family=="Debian"

  - name: install java on redhat
    yum:
      name:
      state: started
    when: ansible_os_family=="RedHat"
    
