---
- hosts: 172.31.12.205 
  become: yes
  tasks:
   - name: i want to execute direct linux command
     command: hostname -f
     register: result

   - name: want tp display first task output
     debug:
       msg: "{{result}}"